# Documentation for branch policy: https://aka.ms/gim/docs/policy/branch-protection

name: SDL
description: Requires one reviewer for merges into main branch
resource: repository
where: 
configuration:
  branchProtectionRules:
    - branchNamePattern: "main"
      requiredApprovingReviewsCount: 1